module.exports.config = {
  name: "chuilientuc",
  version: "3.0.0",
  hasPermssion: 2,
  credits: "Vtuan",
  description: "Spam đến chết 1 nội dung (gọi hồn liên tục)",
  commandCategory: "Spam",
  usages: "[ID người dùng]",
  cooldowns: 1
};
const spamThreads = new Map(); 
function delay(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}
module.exports.run = async function({ api, event, args }) {
  const timedelay = 1;
  const { threadID, messageID } = event;
  if (args[0] === "stop") {
    const state = spamThreads.get(threadID);
    if (state) {
      let stopIndex = state.i; 
      spamThreads.delete(threadID);
      api.sendMessage(`Đã tạm dừng`, threadID, messageID);
    } else {
      api.sendMessage("Làm gì có ai bị chửi đâu?", threadID, messageID);
    }
    return;
  }

  
  var mention = Object.keys(event.mentions)[0];
  if (!mention) return api.sendMessage("Cần phải tag 1 người bạn muốn chửi", event.threadID);
  let name = event.mentions[mention];
  var arraytag = [];
  arraytag.push({ id: mention, tag: name });
  const vtuann = [
    "chó ăn cứt cay 🤣🤣",
      "sủa đê 🤣🤣",
      "chó bú cứt🤣🤣👌",
      "hăng hái đê :)) ",
      "chậm dọ 🤣🤣 ",
      "óc dái cay r🤣🤣 ",
      "ăn hại phát biểu lẹ đê 🤣🤣 ",
      "óc dái :))) ",
      "ổn phải k? ",
      "ngu ớn 🤣🤣👌 ",
      "chó ăn cứt 🐶 ",
      "dái đú :)))) ",
      "yếu dữ ta😏😏 ",
      "con chó đần👉🤣 ",
      "ổn dữ chưa =))) ",
      "run ớn dạ :))) ",
      "óc đú 🤣🤣 ",
      "rồi xong 🤢🤢 ",
      "có thể hăng ko á  ",
      "ẻm cay doài =))) ",
      "cay tuột buồi 👉🤣",
      "ei ei =)) ",
      "em ei :3 ",
      "chạy à ",
      "mày sợ hả 🤢🤢 ",
      "coi ẻm sồn kìa🤣🤣 👌",
      "lại bá à :))) ",
      "sao chậm dữ ",
      "eo oyyy:3 ",
      "hú hú🤨 ",
      "sao ức chế dạ 😏😏 ",
      "con não cún bị chửi kìa 🤣🤣🐶 ",
      "mau đê :)) ",
      "hăng đê :))) ",
      "sủa mau đê =)) ",
      "cần cứu ko :)) ",
      "cố đi :3 ",
      "gáng lên đê :))) ",
      "sủa to lên🤣🤣 ",
      "phò nông thôn 🤢🤢 ",
      "óc cặc tỉnh lẽ =)))) ",
      "khoẻ ko 🤣🤣 ",
      "kkk ",
      "đói à🤣🐶👌 ",
      "ăn chưa à 🤣🤣 ",
      "chưa đk :))) ",
      "thấy kém cõi :)) ",
      "đú cứt kìa :))) ",
      "eo oyyy:3 ",
      "cố đê 🤣🤣 ",
      "thấy mày đơ đơ :))) ",
      "con cave 🤣🤣 ",
      "mạnh lên:))) ",
      "gõ mạnh lên đê:)) ",
      "thấy ngại ngùng z🤣🤘 ",
      "tự nhiên đê ",
      "mệt đk ",
      "cấm m ngưng ",
      "đĩ đầu đinh :))) ",
      "lẹ đê:)) ",
      "mày lag à :)) ",
      "m trầm cảm à :))) ",
      "tâm lí ko vững à :)) ",
      "cần thuốc à :)) ",
      "hấp hối hả🤣🤣 ",
      "khó thở dk :)) ",
      "cần oxi ko :))) ",
      "mày bệnh nặng lắm à :))) ",
      "tuột hứng cha :))) ",
      "tnh gà :))) ",
      "sao chậm chạp v :)) ",
      "óc dái 🤣🤣 ",
      "lồn cụ con đĩ đớ🤣🤣 ",
      "lưu loát lên đê 🤣🤣 ",
      "khựng dạ :))) ",
      "t mạnh lắm phải ko à :))) ",
      ":))) nhỏ mếu à ae ",
      "m nghèo mà ",
      "sợ t lắm à:3 ",
      "hả cu =))) ",
      "thấy tội quá:)) ",
      "thương ẻm cố gắng🤢🤘 ",
      "mà ngu🤣🤣 ",
      ":)) 🤣🤣 ",
      "cay lắm à :)) ",
      "nhạt nhoè v à ",
      "ko cảm hứng để hăng à :))) ",
      "xạo lồn à :))) ",
      "khóc đk :))) ",
      "cave tỉnh lẽ phát biểu:)) ",
      "ra tín hiệu đê :))) ",
      "SOS con dái đú 🤣🤣🤢 ",
      "ớ ớ ớ :))) ",
      "chó ăn cứt :))) ",
      "chó đú sàn 👌🐶 ",
      "ỉa ra máu r à :))) ",
      "nghèo k có nghi lực à:))",
      "phản kháng đê :))) t win à ",
      "kkk ",
      "m chết r à :))) ",
      "m nghèo mà em 😏🤣 ",
      "m thèm cứt t mà:)) ",
      "đĩ mẹ m ngu mà👉🤣 ",
      "m cay tao mà :)) ",
      "con óc cứt thối🤢🤢 ",
      "con đĩ mặt chim🤪🤪 ",
      "ôm hận à 🤨 ",
      "con đĩ nhà núi :))) ",
      "bede bóng lộ =)) ",
      "cn đĩ mẹ mày ",
      "tao từ hình mẹ m mà :)) ",
      "tk phế vật ăn hại😏🤘 ",
      "đú đởn hả con :)) ",
      "m sao dọ ",
      "sủa nè  ",
      "123 sủa😏 ",
      "lẹ nè  ",
      "alo alo hú hú  ",
      "th cầm thú ",
      "m s dạ  ",
      "m sợ mẹ hả  ",
      "lên đi mẹ ko giết cha má m đâu mà 😏 ",
      "hù :)) ",
      "bất ổn hở ",
      "s đó  ",
      "m rớt kìa th gà🤪 ",
      "t cấm m chối nhen ",
      "chối t giết cha má m nè:))) ",
      "hăng xíu lẹ kaka🤢 ",
      "th đần  ",
      "lên mẹ biểu ",
      "k lên t tuyệt chủng m nhen cn thú ",
      "m thích đú ko dạ🤨 ",
      "ko rep = t win nhen  ",
      "cấm chạy nhen ",
      "m mau  ",
      "lên đây ơ ơ  ",
      "th ngu ê ",
      "s á lên đây mẹ sút m chết ",
      "m khóc à 👉🤣",
      "sủa liên tục ơ🤣🤣 ",
      "cầu cứu lũ đú à  ",
      "sục dái nó xem à ",
      "dái thâm v? ",
      "chậm v cn culi🤣🤣👌 ",
      "hoảng loạn à ",
      "bất ổn à 🤮🤮 ",
      "run à ",
      "chạy à  ",
      "đuối à  ",
      "bại chưa 👉😏 ",
      "sủa mau🙄🙄👈 ",
      "mạnh dạn lên  ",
      "nhanh t cho cơ hội cứu má m nè ",
      "cấm mách mẹ ",
      "ảo war hở :)) ",
      "dồn ko  ",
      "đua nè lên sàn t chấp😏👌 ",
      "th chợ búa m sao v ",
      "th đầu buồi mặt chó😢🫵🏻👈🏻 ",
      "cấm hoảng loạn ",
      "lại phải win nữa à🙄🙄 ",
      "kkk ",
      "thằng bê đê bất lực vì mẹ nó bị đụ tung cái lồn:)))  ",
      "con đĩ mẹ mày bất lực vì bị tao chửi mà chỉ biết câm lặng:)))  ",
      "làm màu mà bị tao chửi rung cái con cặc:)))  ",
      "Mẹ mày bị tao đụ lòi hột le:)))  ",
      "thằng bê đê ảo cặc đòi cân và cái kết:)))  ",
      "con đĩ mẹ của mày thèm cứt tao dữ lắm:)))  ",
      "bị tao chửi sảng cặc đéo dám care:)))  ",
      "mạnh lên sao yếu đuối v con:)))  ",
      "mày run cặc chưa con:)))  ",
      "chậm vậy sao cứu được con đĩ mẹ mày nhanh lên đi chứ:)))  ",
      "chết cha nó sồn r  ",
      "con đĩ mẹ mày gào thét đê?😛  ",
      "mày gào lên con?😏  ",
      "sao cay tao dọ?  ",
      "mày sủa đi nè😛  ",
      "sao mày xấu lồn gớm chó dị con?  ",
      "sao cay tao hả😏?  ",
      "sao mày giết mẹ vậy=)))  ",
      "mày gào đi con=)))  ",
      "nào ổn thì đú🤣👈  ",
      "ê bê đê lên ăn hôi lẹ😘  ",
      "mày đú rõ mò  ",
      "sao mày ăn cứt tao😏  ",
      "ai cho mày ăn cứt tao  ",
      "sao mày óc cặc dữ con=)))  ",
      "gặp tao đừng run nha?😂  ",
      "con đĩ mẹ mày thèm cứt tao dữ lắm=)))  ",
      "mày mồ côi mà đúng k🤣👈  ",
      "ai cho mày sủa tao cho mày sủa chưa?  ",
      "bị tao chọc cay hơn con chó luôn=)))  ",
      "cố đi sắp win rồi nè😏  ",
      "chừng nào mày mới làm lại tao dị?  ",
      "mẹ mày sắp tắt thở kìa ê  ",
      "đậu má mày gà mà sủa  ",
      "sủa điên đi mà sủa hăng lên mới vui😘  ",
      "mày mà ngưng một giây là con đĩ mẹ mày bả tắt đường thở á😏  ",
      "ê chó ngu mày sợ tao hả😂  ",
      "mày đú rõ mà sao mày đú dị?  ",
      "mẹ mày chết chưa con=)))  ",
      "ê bê đê sủa điên đi  ",
      "sao mày sủa chậm dị?  ",
      "nào làm lại tao nói đê?  ",
      "bị tao chọc cay hơn con chó luôn😏  ",
      "sủa đi rồi tao tha?  ",
      "sủa điên lên cho mẹ?  ",
      "mày ngưng là con đĩ mẹ mày chết?  ",
      "cay tao lòi dái hả😏  ",
      "não chó cay à?🤣  ",
      "sao mày thảm dị=)))  ",
      "mẹ mày bị tao địt rách màn trinh mà🤪  ",
      "mẹ mày bị tao dã vào lồn=)))  ",
      "địt mẹ mày sướng tê con cặc=)))  ",
      "huhu nhìn mày như con cặc=)))  ",
      "mày loạn luân bà già hả=)))  ",
      "mẹ mày bị tao địt rên ư ử=)))  ",
      "địt mẹ mày sảng khoái quá đi😛  ",
      "tao địt mẹ mày nát lồn mà=)))  ",
      "Ê bóng lồn  ",
      "mẹ mày bị tao cưỡng hiếp=)))  ",
      "mẹ mày đưa lồn chó liếm à🤣👈  ",
      "mày óc cái lồn mà  ",
      "năn nỉ đi tao tha😏  ",
      "bú lồn tao đi🤪  ",
      "mày ẳng gì dị?😏  ",
      "nghe nói mày sợ tao?  ",
      "vô danh cấm sủa?😏 ",
      "gì mày thèm cứt tao hả=)))?  ",
      "sao mày lề mề dị con  ",
      "mày có tuổi hở?😏  ",
      "tuổi lồn ăn tao á😏?  ",
      "tao đụ má mày ná thở mà😛 ",
     "thg ngu va tí kh 🤣🤣 ",
    "vô danh cấm sủa?😏  ",
    "gì mày thèm cứt tao hả=)))?  ",
    "sao mày lề mề dị con  ",
    "mày có tuổi hở?😏  ",
    "tuổi lồn ăn tao á😏?  ",
    "tao đụ má mày ná thở mà😛 ",
    "cấm hoảng loạn ",
    "lại phải win nữa à🙄🙄 ",
    "kkk ",
    "tuột hứng cha :))) ",
    "tnh gà :))) ",
    "sao chậm chạp v :)) ",
    "óc dái 🤣🤣 ",
    "lồn cụ con đĩ đớ🤣🤣 ",
    "lưu loát lên đê 🤣🤣 ",
    "khựng dạ :))) ",
    "t mạnh lắm phải ko à :))) ",
    ":))) nhỏ mếu à ae ",
    "m nghèo mà ",
    "sợ t lắm à:3 ",
    "hả cu =))) ",
    "thấy tội quá:)) ",
    "thương ẻm cố gắng🤢🤘 ",
    "mà ngu🤣🤣 ",
    ":)) 🤣🤣 ",
    "cay lắm à :)) ",
    "nhạt nhoè v à ",
    "ko cảm hứng để hăng à :))) ",
    "xạo lồn à :))) ",
    "khóc đk :))) ",
    "cave tỉnh lẽ phát biểu:)) ",
    "ra tín hiệu đê :))) ",
    "SOS con dái đú 🤣🤣🤢 ",
    "ớ ớ ớ :))) ",
    "chó ăn cứt :))) ",
    "chó đú sàn 👌🐶 ",
    "ỉa ra máu r à :))) ",
    "nghèo k có nghi lực à:)) ",
    "phản kháng đê :))) t win à ",
    "sủa đê 🤣🤣 ",
    "chó bú cứt🤣🤣👌",
    "hăng hái đê :)) ",
    "chậm dọ 🤣🤣 ",
    "óc dái cay r🤣🤣 ",
    "ăn hại phát biểu lẹ đê 🤣🤣 ",
    "óc dái :))) ",
    "ổn phải k? ",
    "ngu ớn 🤣🤣👌 ",
    "chó ăn cứt 🐶 ",
    "dái đú :)))) ",
    "yếu dữ ta😏😏 ",
    "con chó đần👉🤣 ",
    "ổn dữ chưa =))) ",
    "run ớn dạ :))) ",
    "óc đú 🤣🤣 ",
    "rồi xong 🤢🤢 ",
    "có thể hăng ko á  ",
    "ẻm cay doài =))) ",
    "cay tuột buồi 👉🤣",
    "ei ei =)) ",
    "em ei :3 ",
    "chạy à ",
    "mày sợ hả 🤢🤢 ",
    "coi ẻm sồn kìa🤣🤣 👌",
    "lại bá à :))) ",
    "sao chậm dữ ",
    "eo oyyy:3 ",
    "hú hú🤨 ",
    "sao ức chế dạ 😏😏 ",
    "con não cún bị chửi kìa 🤣🤣🐶 ",
    "mau đê :)) ",
    "hăng đê :))) ",
    "sủa mau đê =)) ",
    "tuột hứng cha :))) ",
    "tnh gà :))) ",
    "sao chậm chạp v :)) ",
    "óc dái 🤣🤣 ",
    "lồn cụ con đĩ đớ🤣🤣 ",
    "lưu loát lên đê 🤣🤣 ",
    "khựng dạ :))) ",
    "t mạnh lắm phải ko à :))) ",
    ":))) nhỏ mếu à ae ",
    "m nghèo mà ",
    "sợ t lắm à:3 ",
    "hả cu =))) ",
    "thấy tội quá:)) ",
    "thương ẻm cố gắng🤢🤘 ",
    "mà ngu🤣🤣 ",
    ":)) 🤣🤣 ",
    "cay lắm à :)) ",
    "nhạt nhoè v à ",
    "ko cảm hứng để hăng à :))) ",
    "xạo lồn à :))) ",
    "khóc đk :))) ",
    "cave tỉnh lẽ phát biểu:)) ",
    "ra tín hiệu đê :))) ",
    "SOS con dái đú 🤣🤣🤢 ",
    "ớ ớ ớ :))) ",
    "chó ăn cứt :))) ",
    "chó đú sàn 👌🐶 ",
    "ỉa ra máu r à :))) ",
    "nghèo k có nghi lực à:)) ",
    "phản kháng đê :))) t win à ",
    "cần cứu ko :)) ",
    "cố đi :3 ",
    "gáng lên đê :))) ",
    "sủa to lên🤣🤣 ",
    "phò nông thôn 🤢🤢 ",
    "óc cặc tỉnh lẽ =)))) ",
    "khoẻ ko 🤣🤣 ",
    "kkk ",
    "đói à🤣🐶👌 ",
    "ăn chưa à 🤣🤣 ",
    "chưa đk :))) ",
    "thấy kém cõi :)) ",
    "đú cứt kìa :))) ",
    "eo oyyy:3 ",
    "cố đê 🤣🤣 ",
    "thấy mày đơ đơ :))) ",
    "con cave 🤣🤣 ",
    "mạnh lên:))) ",
    "gõ mạnh lên đê:)) ",
    "thấy ngại ngùng z🤣🤘 ",
    "tự nhiên đê ",
    "mệt đk ",
    "cấm m ngưng ",
    "đĩ đầu đinh :))) ",
    "lẹ đê:)) ",
    "mày lag à :)) ",
    "m trầm cảm à :))) ",
    "tâm lí ko vững à :)) ",
    "cần thuốc à :)) ",
    "hấp hối hả🤣🤣 ",
    "khó thở dk :)) ",
    "cần oxi ko :))) ",
    "mày bệnh nặng lắm à :))) ",
    "tuột hứng cha :))) ",
    "tnh gà :))) ",
    "sao chậm chạp v :)) ",
    "óc dái 🤣🤣 ",
    "lồn cụ con đĩ đớ🤣🤣 ",
    "lưu loát lên đê 🤣🤣 ",
    "khựng dạ :))) ",
    "t mạnh lắm phải ko à :))) ",
    ":))) nhỏ mếu à ae ",
    "m nghèo mà ",
    "sợ t lắm à:3 ",
    "hả cu =))) ",
    "thấy tội quá:)) ",
    "thương ẻm cố gắng🤢🤘 ",
    "mà ngu🤣🤣 ",
    ":)) 🤣🤣 ",
    "cay lắm à :)) ",
    "nhạt nhoè v à ",
    "ko cảm hứng để hăng à :))) ",
    "xạo lồn à :))) ",
    "khóc đk :))) ",
    "cave tỉnh lẽ phát biểu:)) ",
    "ra tín hiệu đê :))) ",
    "SOS con dái đú 🤣🤣🤢 ",
    "ớ ớ ớ :))) ",
    "chó ăn cứt :))) ",
    "chó đú sàn 👌🐶 ",
    "ỉa ra máu r à :))) ",
    "nghèo k có nghi lực à:)) ",
    "phản kháng đê :))) t win à ",
    "kkk ",
    "m chết r à :))) ",
    "m nghèo mà em 😏🤣 ",
    "m thèm cứt t mà:)) ",
    "đĩ mẹ m ngu mà👉🤣 ",
    "m cay tao mà :)) ",
    "con óc cứt thối🤢🤢 ",
    "con đĩ mặt chim🤪🤪 ",
    "ôm hận à 🤨 ",
    "con đĩ nhà núi :))) ",
    "bede bóng lộ =)) ",
    "cn đĩ mẹ mày ",
    "tao từ hình mẹ m mà :)) ",
    "tk phế vật ăn hại😏🤘 ",
    "đú đởn hả con :)) ",
    "m sao dọ ",
    "sủa nè  ",
    "123 sủa😏 ",
    "lẹ nè  ",
    "alo alo hú hú  ",
    "th cầm thú ",
    "m s dạ  ",
    "m sợ mẹ hả  ",
    "lên đi mẹ ko giết cha má m đâu mà 😏 ",
    "hù :)) ",
    "bất ổn hở ",
    "s đó  ",
    "m rớt kìa th gà🤪 ",
    "t cấm m chối nhen ",
    "chối t giết cha má m nè:))) ",
    "hăng xíu lẹ kaka🤢 ",
    "th đần  ",
    "lên mẹ biểu ",
    "k lên t tuyệt chủng m nhen cn thú ",
    "m thích đú ko dạ🤨 ",
    "ko rep = t win nhen  ",
    "cấm chạy nhen ",
    "m mau  ",
    "lên đây ơ ơ  ",
    "th ngu ê ",
    "s á lên đây mẹ sút m chết ",
    "m khóc à 👉🤣 ",
    "sủa liên tục ơ🤣🤣 ",
    "cầu cứu lũ đú à  ",
    "sục dái nó xem à ",
    "dái thâm v? ",
    "chậm v cn culi🤣🤣👌 ",
    "hoảng loạn à ",
    "bất ổn à 🤮🤮 ",
    "run à ",
    "chạy à  ",
    "đuối à  ",
    "tuột hứng cha :))) ",
    "tnh gà :))) ",
    "sao chậm chạp v :)) ",
    "óc dái 🤣🤣 ",
    "lồn cụ con đĩ đớ🤣🤣 ",
    "lưu loát lên đê 🤣🤣 ",
    "khựng dạ :))) ",
    "t mạnh lắm phải ko à :))) ",
    ":))) nhỏ mếu à ae ",
    "m nghèo mà ",
    "sợ t lắm à:3 ",
    "hả cu =))) ",
    "thấy tội quá:)) ",
    "thương ẻm cố gắng🤢🤘 ",
    "mà ngu🤣🤣 ",
    ":)) 🤣🤣 ",
    "cay lắm à :)) ",
    "nhạt nhoè v à ",
    "ko cảm hứng để hăng à :))) ",
    "xạo lồn à :))) ",
    "khóc đk :))) ",
    "cave tỉnh lẽ phát biểu:)) ",
    "ra tín hiệu đê :))) ",
    "SOS con dái đú 🤣🤣🤢 ",
    "ớ ớ ớ :))) ",
    "chó ăn cứt :))) ",
    "chó đú sàn 👌🐶 ",
    "ỉa ra máu r à :))) ",
    "nghèo k có nghi lực à:)) ",
    "phản kháng đê :))) t win à ",
    "tuột hứng cha :))) ",
    "tnh gà :))) ",
    "sao chậm chạp v :)) ",
    "óc dái 🤣🤣 ",
    "lồn cụ con đĩ đớ🤣🤣 ",
    "lưu loát lên đê 🤣🤣 ",
    "khựng dạ :))) ",
    "t mạnh lắm phải ko à :))) ",
    ":))) nhỏ mếu à ae ",
    "m nghèo mà ",
    "sợ t lắm à:3 ",
    "hả cu =))) ",
    "thấy tội quá:)) ",
    "thương ẻm cố gắng🤢🤘 ",
    "mà ngu🤣🤣 ",
    ":)) 🤣🤣 ",
    "cay lắm à :)) ",
    "nhạt nhoè v à ", 
    "ko cảm hứng để hăng à :))) ",
    "xạo lồn à :))) ",
    "khóc đk :))) ",
    "cave tỉnh lẽ phát biểu:)) ",
    "ra tín hiệu đê :))) ",
    "SOS con dái đú 🤣🤣🤢 ",
    "ớ ớ ớ :))) ",
    "chó ăn cứt :))) ",
    "chó đú sàn 👌🐶 ",
    "ỉa ra máu r à :))) ",
    "nghèo k có nghi lực à:)) ",
    "phản kháng đê :))) t win à ",
    "bại chưa 👉😏 ",
    "sủa mau🙄🙄👈 ",
    "mạnh dạn lên  ",
    "nhanh t cho cơ hội cứu má m nè ",
    "tuột hứng cha :))) ",
    "tnh gà :))) ",
    "sao chậm chạp v :)) ",
    "óc dái 🤣🤣 ",
    "lồn cụ con đĩ đớ🤣🤣 ",
    "lưu loát lên đê 🤣🤣 ",
    "khựng dạ :))) ",
    "t mạnh lắm phải ko à :))) ",
    ":))) nhỏ mếu à ae ",
    "m nghèo mà ",
    "sợ t lắm à:3 ",
    "hả cu =))) ",
    "thấy tội quá:)) ",
    "thương ẻm cố gắng🤢🤘 ",
    "mà ngu🤣🤣 ",
    ":)) 🤣🤣 ",
    "cay lắm à :)) ",
    "nhạt nhoè v à ",
    "ko cảm hứng để hăng à :))) ",
    "xạo lồn à :))) ",
    "ra tín hiệu đê :))) ",
    "cố tí em ",
    "mếu à ",
    "sao mếu kìa ",
    "tao đã cho m mếu đâu ",
    "va lẹ eii ",
    "sao kìa ",
    "từ bỏ r à ",
    "mạnh mẽ tí đi nà ",
    "cố eii ",
    ":))) ",
    "sợ tao à ",
    "sao sợ tao kìa ",
    "tao đang hành m mà ",
    "bịa à ",
    "cay :))))) ",
    "cố eiii ",
    "hăng tiếp đi ",
    "tới sáng k em ",
    "k tới sáng à ",
    "SOS con dái đú 🤣🤣🤢 ",
    "ớ ớ ớ :))) ",
    "sủa đi rồi tao tha?  ",
    "sủa điên lên cho mẹ?  ",
    "mày ngưng là con đĩ mẹ mày chết?  ",
    "cay tao lòi dái hả😏  ",
    "não chó cay à?🤣  ",
    "sao mày thảm dị=)))  ",
    "mẹ mày bị tao địt rách màn trinh mà🤪  ",
    "mẹ mày bị tao dã vào lồn=)))  ",
    "địt mẹ mày sướng tê con cặc=)))  ",
    "huhu nhìn mày như con cặc=)))  ",
    "mày loạn luân bà già hả=)))  ",
    "mẹ mày bị tao địt rên ư ử=)))  ",
    "địt mẹ mày sảng khoái quá đi😛  ",
    "tao địt mẹ mày nát lồn mà=)))  ",
    "Ê bóng lồn  ",
    "mẹ mày bị tao cưỡng hiếp=)))  ",
    "mẹ mày đưa lồn chó liếm à🤣👈  ",
    "mày óc cái lồn mà  ",
    "năn nỉ đi tao tha😏  ",
    "bú lồn tao đi🤪  ",
    "mày ẳng gì dị?😏  ",
    "nghe nói mày sợ tao?  ",
    "vô danh cấm sủa?😏  ",
    "gì mày thèm cứt tao hả=)))?  ",
    "sao mày lề mề dị con  ",
    "mày có tuổi hở?😏  ",
    "tuổi lồn ăn tao á😏?  ",
    "tao đụ má mày ná thở mà😛 ",
    "chó ăn cứt :))) ",
    "chó đú sàn 👌🐶 ",
    "ỉa ra máu r à :))) ",
    "nghèo k có nghi lực à:)) ",
    "phản kháng đê :))) t win à ",
    "cấm mách mẹ ",
    "ảo war hở :)) ",
    "dồn ko  ",
    "đua nè lên sàn t chấp😏👌 ",
    "th chợ búa m sao v ",
    "th đầu buồi mặt chó😢🫵🏻👈🏻 ",
    "m còn ổn không vậy ",
    "tinh thần bất ổn à=) ",
    "cấm hoảng loạn ",
    "lại phải win nữa à🙄🙄 ",
    "kkk ",
    "coi nhỏ khóc đỏ mắt luôn kìa😂 ",
    "hphuc chửi thấm quá mà ",
    "cay cay cay ",
    "cha bá quá à con đĩ😂 ",
    "thg có mẹ bán cám lợn lìa=)) ",
    "mẹ mày làm cám lợn với đĩ à ",
    "nghề phụ là osin à=)) ",
    "th xong nước mắt cả sấu à=)) ",
    "kkk ",
    "nhì mặt m tởm gớm ",
    "mặt toàn mụn với rỗ kìa=)) ",
    "trông mà phát ghê ",
    "miệng hôi sữa với ",
    "vắt mũi ch sạch mà đú war à ",
    "ai cho mày vào sàn vậy con đú=) ",
    "hả hả cgi ",
    "mẹ đĩ của m dắt m vào sàn à=)) ",
    "mẹ mày bú cặc t để m được vào sàn mà ",
    "sao ức chế dạ 😏😏 ",
    "con não cún bị chửi kìa 🤣🤣🐶 ",
    "mau đê :)) ",
    "hăng đê :))) ",
    "sủa mau đê =)) ",
    "tuột hứng cha :))) ",
    "tnh gà :))) ",
    "sao chậm chạp v :)) ",
    "óc dái 🤣🤣 ",
    "lồn cụ con đĩ đớ🤣🤣 ",
    "lưu loát lên đê 🤣🤣 ",
    "khựng dạ :))) ",
    "t mạnh lắm phải ko à :))) ",
    ":))) nhỏ mếu à ae ",
    "m nghèo mà ",
    "sợ t lắm à:3 ",
    "hả cu =))) ",
    "thấy tội quá:)) ",
    "thương ẻm cố gắng🤢🤘 ",
    "mà ngu🤣🤣 ",
    ":)) 🤣🤣 ",
    "cay lắm à :)) ",
    "nhạt nhoè v à ",
    "ko cảm hứng để hăng à :))) ",
    "xạo lồn à :))) ",
    "khóc đk :))) ",
    "cave tỉnh lẽ phát biểu:)) ",
    "ra tín hiệu đê :))) ",
    "SOS con dái đú 🤣🤣🤢 ",
    "ớ ớ ớ :))) ",
    "chó ăn cứt :))) ",
    "chó đú sàn 👌🐶 ",
    "ỉa ra máu r à :))) ",
    "nghèo k có nghi lực à:)) ",
    "phản kháng đê :))) t win à ",
    "tuột hứng cha :))) ",
    "tnh gà :))) ",
    "sao chậm chạp v :)) ",
    "óc dái 🤣🤣 ",
    "lồn cụ con đĩ đớ🤣🤣 ",
    "lưu loát lên đê 🤣🤣 ",
    "khựng dạ :))) ",
    "t mạnh lắm phải ko à :))) ",
    ":))) nhỏ mếu à ae ",
    "m nghèo mà ",
    "sợ t lắm à:3 ",
    "clm cái thg có con mẹ làm đĩ=)) ",
    "tẩy chay nó đi ae ",
    "cặn bã đéo xứng trong xh😂😂 ",
    "thg láo lồn ảo đá chân kinh=)) ",
    "đập đá hít cần sa nhiều xong sủa bậy à ",
    "sao sao m câm hở con ",
    "m cáu mag dk=)) ",
    "tao là chúa mà m ",
    "m cay tao là điều đư nhiên😂 ",
    "sao mày thảm dị=)))  ",
    "mẹ mày bị tao địt rách màn trinh mà🤪  ",
    "mẹ mày bị tao dã vào lồn=)))  ",
    "địt mẹ mày sướng tê con cặc=)))  ",
    "huhu nhìn mày như con cặc=)))  ",
    "mày loạn luân bà già hả=)))  ",
    "mẹ mày bị tao địt rên ư ử=)))  ",
    "địt mẹ mày sảng khoái quá đi😛 ",
    "tao địt mẹ mày nát lồn mà=)))  ",
    "Ê bóng lồn  ",
      "sao m yếu v ",
    "cố tí nữa ",
    "sao kìa chậm à ",
    "hăng hái lên tí chứ ",
    "tới sáng đi em eii ",
    "cố gắng tí eii ",
    "k đc à ",
    "con eii cố de ",
    "sao m câm kìa ",
    "gà j ",
    "tnh gà ",
    "m gà mà ",
    "dk à ",
    "đúng mà ",
    "cãi à ",
    "mày còn gì khác k ",
    "học lỏm kìa ",
    "cố tí em ",
    "mếu à ",
    "sao mếu kìa ",
    "tao đã cho m mếu đâu ",
    "va lẹ eii ",
    "sao kìa ",
    "từ bỏ r à ",
    "mạnh mẽ tí đi nà ",
    "cố eii ",
    ":))) ",
    "sợ tao à ",
    "sao sợ tao kìa ",
    "tao đang hành m mà ",
    "bịa à ",
    "cay :))))) ",
    "cố eiii ",
    "hăng tiếp đi ",
    "tới sáng k em ",
    "k tới sáng à ",
    "chán v ",
    "m gà mà ",
    "log acc thay phiên à ",
    "coi tụi nó dồn ngu kìa ",
    "ae ơiii ",
    "lại win à ",
    "lại win r ",
    "lũ cặc cay tao lắm🤣🤣 ",
    "cố lên đê ",
    "nó treo à ae🤣 ",
    "yếu đến thế à ",
    "sao kìa ",
    "khóc kìa ",
    "cầu cứu lẹ ei ",
    "ai cứu đc m à:)) ",
    "tao bá mà ",
    "sao m gà thế ",
    "hăng lẹ cho tao ",
    "con chó eiii🤣 ",
    "ổn k em ",
    "kh ổn r à ",
    "xin tha eii ",
    "mẹ mày ngu à ",
    "bú cặc cha m k em ",
    "thg giả gái:)) ",
    "coi nó ngu kìa ae ",
    "con chó này giả ngu à ",
    "m ổn k ",
    "mồ côi kìa ",
    "sao v sợ r à ",
    "mẹ mày bị tao cưỡng hiếp=)))  ",
    "mẹ mày đưa lồn chó liếm à🤣👈  ",
    "mày óc cái lồn mà  ",
    "năn nỉ đi tao tha😏  ",
    "bú lồn tao đi🤪  ",
    "mày ẳng gì dị?😏  ",
    "nghe nói mày sợ tao?  ",
    "vô danh cấm sủa?😏  ",
    "gì mày thèm cứt tao hả=)))?  ",
    "sao mày lề mề dị con  ",
    "mày có tuổi hở?😏  ",
    "tuổi lồn ăn tao á😏?  ",
      "sủa đê 🤣🤣 ",
    "chó bú cứt🤣🤣👌 ",
    "hăng hái đê :))  ",
    "chậm dọ 🤣🤣 ",
    "óc dái cay r🤣🤣 ",
    "ăn hại phát biểu lẹ đê 🤣🤣 ",
    "óc dái :))) ",
    "ổn phải k? ",
    "ngu ớn 🤣🤣👌 ",
    "chó ăn cứt 🐶 ",
    "dái đú :)))) ",
    "yếu dữ ta😏😏 ",
    "con chó đần👉🤣 ",
    "ổn dữ chưa =))) ",
    "run ớn dạ :))) ",
    "óc đú 🤣🤣 ",
    "rồi xong 🤢🤢 ",
    "có thể hăng ko á  ",
    "ẻm cay doài =))) ",
    "cay tuột buồi 👉🤣 ",
    "ei ei =)) ",
    "em ei :3 ",
    "chạy à ",
    "mày sợ hả 🤢🤢 ",
    "coi ẻm sồn kìa🤣🤣 👌 ",
    "cần oxi ko :))) ",
    "mày bệnh nặng lắm à:))) ",
    "tuột hứng cha :))) ",
    "tnh gà :))) ",
    "sao chậm chạp v :)) ",
    "óc dái 🤣🤣 ",
    "lồn cụ con đĩ đớ🤣🤣 ",
    "lưu loát lên đê 🤣🤣 ",
    "khựng dạ :))) ",
    "t mạnh lắm phải ko à :))) ",
    ":))) nhỏ mếu à ae ",
    "m nghèo mà ",
    "sợ t lắm à:3 ",
    "hả cu =))) ",
    "thấy tội quá:)) ",
    "thương ẻm cố gắng🤢🤘 ",
    "mà ngu🤣🤣 ",
    ":)) 🤣🤣 ",
    "cay lắm à :)) ",
    "nhạt nhoè v à ",
    "ko cảm hứng để hăng à :))) ",
    "xạo lồn à :))) ",
    "khóc đk :))) ",
    "cave tỉnh lẽ phát biểu:)) ",
    "ra tín hiệu đê :))) ",
    "SOS con dái đú 🤣🤣🤢 ",
    "ớ ớ ớ :))) ",
    "chó ăn cứt :))) ",
    "chó đú sàn 👌🐶 ",
    "ỉa ra máu r à :))) ",
    "nghèo k có nghi lực à:)) ",
    "phản kháng đê :))) t win à ",
    "kkk ",
    "m chết r à :))) ",
    "m nghèo mà em 😏🤣 ",
    "m thèm cứt t mà:)) ",
    "đĩ mẹ m ngu mà👉🤣 ",
    "m cay tao mà :)) ",
    "con óc cứt thối🤢🤢 ",
    "con đĩ mặt chim🤪🤪 ",
    "ôm hận à 🤨 ",
    "con đĩ nhà núi :))) ",
    "bede bóng lộ =)) ",
    "cn đĩ mẹ mày ",
    "tao từ hình mẹ m mà:)) ",
    "tk phế vật ăn hại😏🤘 ",
    "đú đởn hả con :)) ",
    "m sao dọ ",
    "sủa nè  ",
    "123 sủa😏 ",
    "lẹ nè  ",
    "alo alo hú hú  ",
    "th cầm thú ",
    "m s dạ  ",
    "m sợ mẹ hả  ",
    "lên đi mẹ ko giết cha má m đâu mà 😏 ",
    "hù :)) ",
    "bất ổn hở ",
    "s đó  ",
    "m rớt kìa th gà🤪 ",
    "t cấm m chối nhen ",
    "chối t giết cha má m nè:))) ",
    "hăng xíu lẹ kaka🤢 ",
    "th đần  ",
    "lên mẹ biểu ",
    "k lên t tuyệt chủng m nhen cn thú ",
    "m thích đú ko dạ🤨 ",
    "ko rep = t win nhen  ",
    "cấm chạy nhen ",
    "m mau  ",
    "lên đây ơ ơ  ",
    "th ngu ê ",
    "s á lên đây mẹ sút m chết ",
    "m khóc à 👉🤣 ",
    "sủa liên tục ơ🤣🤣 ",
    "cầu cứu lũ đú à  ",
    "sục dái nó xem à ",
    "dái thâm v? ",
    "chậm v cn culi🤣🤣👌 ",
    "hoảng loạn à ",
    "bất ổn à 🤮🤮 ",
    "run à ",
    "chạy à  ",
    "đuối à  ",
    "bại chưa 👉😏 ",
    "sủa mau🙄🙄👈 ",
    "mạnh dạn lên  ",
    "nhanh t cho cơ hội cứu má m nè ",
    "cấm mách mẹ ",
    "ảo war hở :)) ",
    "dồn ko  ",
    "đua nè lên sàn t chấp😏👌 ",
      "thằng bê đê bất lực vì mẹ nó bị đụ tung cái lồn:)))  ",
    "con đĩ mẹ mày bất lực vì bị tao chửi mà chỉ biết câm lặng:)))  ",
    "làm màu mà bị tao chửi rung cái con cặc:))) ",
    "phản kháng đê :))) t win à ",
    "tuột hứng cha :))) ",
    "tnh gà :))) ",
    "sao chậm chạp v :)) ",
    "óc dái 🤣🤣 ",
    "lồn cụ con đĩ đớ🤣🤣 ",
    "lưu loát lên đê 🤣🤣 ",
    "khựng dạ :))) ",
    "t mạnh lắm phải ko à :))) ",
    "phản kháng đê :))) t win à ",
    "tuột hứng cha :))) ",
    "tnh gà :))) ",
    "sao chậm chạp v :)) ",
    "óc dái 🤣🤣 ",
    "lồn cụ con đĩ đớ🤣🤣 ",
    "lưu loát lên đê 🤣🤣 ",
    "khựng dạ :))) ",
    "t mạnh lắm phải ko à :))) ",
    "Mẹ mày bị tao đụ lòi hột le:)))  ",
    "thằng bê đê ảo cặc đòi cân và cái kết:)))  ",
    "con đĩ mẹ của mày thèm cứt tao dữ lắm:)))  ",
    "bị tao chửi sảng cặc đéo dám care:)))  ",
    "mạnh lên sao yếu đuối v con:)))  ",
    "mày run cặc chưa con:)))  ",
    "chậm vậy sao cứu được con đĩ mẹ mày nhanh lên đi chứ:)))  ",
    "chết cha nó sồn r  ",
    "con đĩ mẹ mày gào thét đê?😛  ",
    "mày gào lên con?😏  ",
    "sao cay tao dọ?  ",
    "mày sủa đi nè😛  ",
    "sao mày xấu lồn gớm chó dị con?  ",
    "sao cay tao hả😏?  ",
    "sao mày giết mẹ vậy=))) ",
    "sủa đi rồi tao tha?  ",
    "sủa điên lên cho mẹ?  ",
    "mày ngưng là con đĩ mẹ mày chết?  ",
    "cay tao lòi dái hả😏  ",
    "não chó cay à?🤣  ",
    "sao mày thảm dị=)))  ",
    "mẹ mày bị tao địt rách màn trinh mà🤪  ",
    "mẹ mày bị tao dã vào lồn=)))  ",
    "địt mẹ mày sướng tê con cặc=)))  ",
    "huhu nhìn mày như con cặc=)))  ",
    "mày loạn luân bà già hả=)))  ",
    "mẹ mày bị tao địt rên ư ử=)))  ",
    "địt mẹ mày sảng khoái quá đi😛  ",
    "tao địt mẹ mày nát lồn mà=)))  ",
    "Ê bóng lồn  ",
    "mẹ mày bị tao cưỡng hiếp=)))  ",
    "mẹ mày đưa lồn chó liếm à🤣👈  ",
    "mày óc cái lồn mà  ",
    "năn nỉ đi tao tha😏  ",
    "bú lồn tao đi🤪  ",
    "mày ẳng gì dị?😏  ",
    "nghe nói mày sợ tao?  ",
    "vô danh cấm sủa?😏  ",
    "gì mày thèm cứt tao hả=)))?  ",
    "sao mày lề mề dị con  ",
    "mày có tuổi hở?😏  ",
    "tuổi lồn ăn tao á😏?  ",
    "tao đụ má mày ná thở mà😛 ",
    "chó ăn cứt :))) ",
    "chó đú sàn 👌🐶 ",
    "ỉa ra máu r à :))) ",
    "nghèo k có nghi lực à:)) ",
    "phản kháng đê :))) t win à ",
    "kkk",
    "m chết r à :))) ",
    "m nghèo mà em 😏🤣 ",
    "m thèm cứt t mà:)) ",
    "đĩ mẹ m ngu mà👉🤣 ",
    "m cay tao mà :)) ",
    "con óc cứt thối🤢🤢 ",
    "con đĩ mặt chim🤪🤪 ",
    "ôm hận à 🤨 ",
    "con đĩ nhà núi :))) ",
    "bede bóng lộ =)) ",
    "cn đĩ mẹ mày ",
    "tao từ hình mẹ m mà :)) ",
    "tk phế vật ăn hại😏🤘 ",
    "đú đởn hả con :)) ",
    "m sao dọ ",
    "sủa nè ",
    "123 sủa😏 ",
    "lẹ nè ",
    "alo alo hú hú ",
    "th cầm thú ",
    "m s dạ ",
    "m sợ mẹ hả ",
    "lên đi mẹ ko giết cha má m đâu mà 😏 ",
    "hù :)) ",
    "bất ổn hở ",
    "s đó ",
    "m rớt kìa th gà🤪 ",
    "t cấm m chối nhen ",
    "chối t giết cha má m nè:))) ",
    "hăng xíu lẹ kaka🤢 ",
    "th đần ",
    "lên mẹ biểu ",
    "k lên t tuyệt chủng m nhen cn thú ",
    "m thích đú ko dạ🤨 ",
    "ko rep = t win nhen ",
    "cấm chạy nhen ",
    "m mau ",
    "lên đây ơ ơ ",
    "th ngu ê ",
    "s á lên đây mẹ sút m chết ",
    "m khóc à 👉🤣 ",
    "sủa liên tục ơ🤣🤣 ",
    "cầu cứu lũ đú à ",
    "sục dái nó xem à ",
    "dái thâm v? ",
    "chậm v cn culi🤣🤣👌 ",
    "hoảng loạn à ",
    "bất ổn à 🤮🤮 ",
    "run à ",
    "chạy à ",
    "đuối à ",
    "bại chưa 👉😏 ",
    "sủa mau🙄🙄👈 ",
    "mạnh dạn lên. ",
    "nhanh t cho cơ hội cứu má m nè ",
    "cấm mách mẹ ",
    "ảo war hở :)) ",
    "dồn ko ",
    "sủa đi rồi tao tha?  ",
    "sủa điên lên cho mẹ?  ",
    "mày ngưng là con đĩ mẹ mày chết?  ",
    "cay tao lòi dái hả😏  ",
    "não chó cay à?🤣  ",
    "sao mày thảm dị=)))  ",
    "mẹ mày bị tao địt rách màn trinh mà🤪  ",
    "mẹ mày bị tao dã vào lồn=)))  ",
    "địt mẹ mày sướng tê con cặc=)))  ",
    "huhu nhìn mày như con cặc=)))  ",
    "mày loạn luân bà già hả=)))  ",
    "mẹ mày bị tao địt rên ư ử=)))  ",
    "địt mẹ mày sảng khoái quá đi😛  ",
    "tao địt mẹ mày nát lồn mà=)))  ",
    "Ê bóng lồn  ",
    "mẹ mày bị tao cưỡng hiếp=)))  ",
    "mẹ mày đưa lồn chó liếm à🤣👈  ",
    "mày óc cái lồn mà  ",
    "năn nỉ đi tao tha😏  ",
    "bú lồn tao đi🤪  ",
    "mày ẳng gì dị?😏  ",
    "nghe nói mày sợ tao?  ",
    "vô danh cấm sủa?😏  ",
    "gì mày thèm cứt tao hả=)))?  ",
    "sao mày lề mề dị con  ",
    "mày có tuổi hở?😏  ",
    "tuổi lồn ăn tao á😏?  ",
    "tao đụ má mày ná thở mà😛 ",
    "đua nè lên sàn t chấp😏👌",
    "th chợ búa m sao v ",
    "th đầu buồi mặt chó😢🫵🏻👈🏻 ",
    "phản kháng đê :))) t win à ",
    "tuột hứng cha :))) ",
    "tnh gà :))) ",
    "sao chậm chạp v :)) ",
    "óc dái 🤣🤣 ",
    "lồn cụ con đĩ đớ🤣🤣 ",
    "lưu loát lên đê 🤣🤣 ",
    "khựng dạ :))) ",
    "t mạnh lắm phải ko à :))) ",
    "cố tí em ",
    "mếu à ",
    "sao mếu kìa ",
    "tao đã cho m mếu đâu ",
    "va lẹ eii ",
    "sao kìa ",
    "từ bỏ r à ",
    "mạnh mẽ tí đi nà ",
    "cố eii ",
    ":))) ",
    "sợ tao à ",
    "sao sợ tao kìa ",
    "tao đang hành m mà ",
    "bịa à ",
    "cay :))))) ",
    "cố eiii ",
    "hăng tiếp đi ",
    "tới sáng k em ",
    "k tới sáng à ",
    "phản kháng đê :))) t win à ",
    "tuột hứng cha :))) ",
    "tnh gà :))) ",
    "sao chậm chạp v :)) ",
    "óc dái 🤣🤣 ",
    "lồn cụ con đĩ đớ🤣🤣 ",
    "lưu loát lên đê 🤣🤣 ",
    "khựng dạ :))) ",
    "t mạnh lắm phải ko à :))) ","cố tí em ",
    "mếu à ",
    "sao mếu kìa ",
    "tao đã cho m mếu đâu ",
    "va lẹ eii ",
    "sao kìa ",
    "từ bỏ r à ",
    "mạnh mẽ tí đi nà ",
    "cố eii ",
    ":))) ",
    "sợ tao à ",
    "sao sợ tao kìa ",
    "tao đang hành m mà ",
    "bịa à ",
    "cay :))))) ",
    "cố eiii ",
    "hăng tiếp đi ",
    "tới sáng k em ",
    "k tới sáng à ",
    "sủa đi rồi tao tha?  ",
    "sủa điên lên cho mẹ?  ",
    "mày ngưng là con đĩ mẹ mày chết?  ",
    "cay tao lòi dái hả😏  ",
    "não chó cay à?🤣  ",
    "sao mày thảm dị=)))  ",
    "mẹ mày bị tao địt rách màn trinh mà🤪  ",
    "mẹ mày bị tao dã vào lồn=)))  ",
    "địt mẹ mày sướng tê con cặc=)))  ",
    "huhu nhìn mày như con cặc=)))  ",
    "mày loạn luân bà già hả=)))  ",
    "mẹ mày bị tao địt rên ư ử=)))  ",
    "địt mẹ mày sảng khoái quá đi😛  ",
    "tao địt mẹ mày nát lồn mà=)))  ",
    "Ê bóng lồn  ",
    "mẹ mày bị tao cưỡng hiếp=)))  ",
    "mẹ mày đưa lồn chó liếm à🤣👈  ",
    "mày óc cái lồn mà  ",
    "năn nỉ đi tao tha😏  ",
    "bú lồn tao đi🤪  ",
    "mày ẳng gì dị?😏  ",
    "nghe nói mày sợ tao?  ",
    "vô danh cấm sủa?😏  ",
    "gì mày thèm cứt tao hả=)))?  ",
    "sao mày lề mề dị con  ",
    "mày có tuổi hở?😏  ",
    "tuổi lồn ăn tao á😏?  ",
    "tao đụ má mày ná thở mà😛 ",
    "phản kháng đê :))) t win à ",
    "tuột hứng cha :))) ",
    "tnh gà :))) ",
    "sao chậm chạp v :)) ",
    "óc dái 🤣🤣 ",
    "lồn cụ con đĩ đớ🤣🤣 ",
    "lưu loát lên đê 🤣🤣 ",
    "khựng dạ :))) ",
    "t mạnh lắm phải ko à :))) ",
    "cố tí em ",
    "mếu à ",
    "sao mếu kìa ",
    "tao đã cho m mếu đâu ",
    "va lẹ eii ",
    "sao kìa ",
    "từ bỏ r à ",
    "mạnh mẽ tí đi nà ",
    "cố eii ",
    ":))) ",
    "sợ tao à ",
    "sao sợ tao kìa ",
    "tao đang hành m mà ",
    "bịa à ",
    "cay :))))) ",
    "cố eiii ",
    "hăng tiếp đi ",
    "tới sáng k em ",
    "k tới sáng à ",
    "sủa đi rồi tao tha?  ",
    "sủa điên lên cho mẹ?  ",
    "mày ngưng là con đĩ mẹ mày chết?  ",
    "cay tao lòi dái hả😏  ",
    "não chó cay à?🤣  ",
    "sao mày thảm dị=)))  ",
    "mẹ mày bị tao địt rách màn trinh mà🤪  ",
    "mẹ mày bị tao dã vào lồn=)))  ",
    "địt mẹ mày sướng tê con cặc=)))  ",
    "huhu nhìn mày như con cặc=)))  ",
    "mày loạn luân bà già hả=)))  ",
    "mẹ mày bị tao địt rên ư ử=)))  ",
    "địt mẹ mày sảng khoái quá đi😛  ",
    "tao địt mẹ mày nát lồn mà=)))  ",
    "Ê bóng lồn  ",
    "mẹ mày bị tao cưỡng hiếp=)))  ",
    "mẹ mày đưa lồn chó liếm à🤣👈  ",
    "mày óc cái lồn mà  ",
    "năn nỉ đi tao tha😏  ",
    "bú lồn tao đi🤪  ",
    "mày ẳng gì dị?😏  ",
    "nghe nói mày sợ tao?  ",
    "vô danh cấm sủa?😏  ",
    "gì mày thèm cứt tao hả=)))?  ",
    "sao mày lề mề dị con  ",
    "mày có tuổi hở?😏  ",
    "tuổi lồn ăn tao á😏?  ",
    "tao đụ má mày ná thở mà😛 ",
    "phản kháng đê :))) t win à ",
    "tuột hứng cha :))) ",
    "tnh gà :))) ",
    "sao chậm chạp v :)) ",
    "óc dái 🤣🤣 ",
    "lồn cụ con đĩ đớ🤣🤣 ",
    "lưu loát lên đê 🤣🤣 ",
    "khựng dạ :))) ",
    "t mạnh lắm phải ko à :))) ",
    "cố tí em ",
    "mếu à ",
    "sao mếu kìa ",
    "tao đã cho m mếu đâu ",
    "va lẹ eii ",
    "sao kìa ",
    "từ bỏ r à ",
    "mạnh mẽ tí đi nà ",
    "cố eii ",
    ":))) ",
    "sợ tao à ",
    "sao sợ tao kìa ",
    "tao đang hành m mà ",
    "bịa à ",
    "cay :))))) ",
    "cố eiii ",
    "hăng tiếp đi ",
    "tới sáng k em ",
    "k tới sáng à ",
    "sủa đi rồi tao tha?  ",
    "sủa điên lên cho mẹ?  ",
    "mày ngưng là con đĩ mẹ mày chết?  ",
    "cay tao lòi dái hả😏  ",
    "não chó cay à?🤣  ",
    "sao mày thảm dị=)))  ",
    "mẹ mày bị tao địt rách màn trinh mà🤪  ",
    "mẹ mày bị tao dã vào lồn=)))  ",
    "địt mẹ mày sướng tê con cặc=)))  ",
    "huhu nhìn mày như con cặc=)))  ",
    "mày loạn luân bà già hả=)))  ",
    "mẹ mày bị tao địt rên ư ử=)))  ",
    "địt mẹ mày sảng khoái quá đi😛  ",
    "tao địt mẹ mày nát lồn mà=)))  ",
    "Ê bóng lồn  ",
    "mẹ mày bị tao cưỡng hiếp=)))  ",
    "mẹ mày đưa lồn chó liếm à🤣👈  ",
    "mày óc cái lồn mà  ",
    "năn nỉ đi tao tha😏  ",
    "bú lồn tao đi🤪  ",
    "mày ẳng gì dị?😏  ",
    "nghe nói mày sợ tao?  ",
    "vô danh cấm sủa?😏  ",
    "gì mày thèm cứt tao hả=)))?  ",
    "sao mày lề mề dị con  ",
    "mày có tuổi hở?😏  ",
    "tuổi lồn ăn tao á😏?  ",
    "tao đụ má mày ná thở mà😛 ",
    "vô danh cấm sủa?😏  ",
    "gì mày thèm cứt tao hả=)))?  ",
    "sao mày lề mề dị con  ",
    "mày có tuổi hở?😏  ",
    "tuổi lồn ăn tao á😏?  ",
    "tao đụ má mày ná thở mà😛 ",
    "cấm hoảng loạn ",
    "lại phải win nữa à🙄🙄 ",
    "kkk anh bá mà ",
    "cấm hoảng loạn ",
    "lại phải win nữa à🙄🙄 ",
    "phản kháng đê :))) t win à ",
    "tuột hứng cha :))) ",
    "tnh gà :))) ",
    "sao chậm chạp v :)) ",
    "óc dái 🤣🤣 ",
    "lồn cụ con đĩ đớ🤣🤣 ",
    "lưu loát lên đê 🤣🤣 ",
    "khựng dạ :))) ",
    "t mạnh lắm phải ko à :))) ",
    "vô danh cấm sủa?😏  ",
    "gì mày thèm cứt tao hả=)))?  ",
    "sao mày lề mề dị con  ",
    "mày có tuổi hở?😏  ",
    "tuổi lồn ăn tao á😏?  ",
    "tao đụ má mày ná thở mà😛 ",
    "cấm hoảng loạn ",
    "lại phải win nữa à🙄🙄 ",
    "akakaka ",
      "th cầm thú ",
    "Ah cúng m nè? ",
    "M có sức ảnh hưởng hả ccho dốt🫵🤣  ",
    "lên đi mẹ ko giết cha má m đâu mà 😏 ",
    "Cha mày đụ heo sinh ra mày đk dog  :)) ",
    "bất ổn hở ",
    "s đó  ",
    "m ớt t mà thg gà🤪 ",
    "t cấm m chối nhen ",
    "chối t giết cha má m nè:))) ",
    "hăng xíu lẹ kaka🤢 ",
    "th đần  ",
    "M CÂM = MẸ M CHẾT ",
    "k lên t tuyệt chủng m nhen cn thú ",
    "m thích đú ko dạ🤨 ",
    "ko rep = t win nhen  ",
    "cấm chạy nhen ",
    "câm là cha win đó nha culi ",
    "lên đây ơ ơ  ",
    "Nhìn mặt mày xấu vãi  ",
    "THẰNG ÓC LỒN MỒ CÔI ",
    "CHA CHO M CÂM CHƯA👉🤣 ",
    "CHA ĐẤNG MXH MÀ🤣🤣 ",
    "ĐĨ MẸ THỨ TINH TRÙNG KHUYẾT TẬT  ",
    "sục dái nó xem à ",
      "ko rep = t win nhen  ",
    "cấm chạy nhen ",
    "câm là cha win đó nha culi ",
    "lên đây ơ ơ  ",
    "Nhìn mặt mày xấu vãi  ",
    "THẰNG ÓC LỒN MỒ CÔI ",
    "CHA CHO M CÂM CHƯA👉🤣 ",
    "CHA ĐẤNG MXH MÀ🤣🤣 ",
    "ĐĨ MẸ THỨ TINH TRÙNG KHUYẾT TẬT  ",
    "sục dái nó xem à ",
    "dái thâm v? ",
    "chậm v cn culi🤣🤣👌 ",
    "ANH BÁ MÀ ",
    "bất ổn à 🤮🤮 ",
    "Sợ tao đến thg cay m cha tao nên chặt cu kìa  ",
    "chạy à  ",
    "đuối à  ",
    "bại chưa 👉😏 ",
    "sủa mau🙄🙄👈 ",
    "mạnh dạn lên  ",
    "nhanh t cho cơ hội cứu má m nè ",
    "cấm mách mẹ ",
    "ảo war hở :)) ",
    "hjhj  ",
    "cố lên sắp win r á😏👌 ",
    "xin win nhé :( ",
    "nhé😢🫵🏻👈🏻 ",
    "cố lên kkkk gần bại r đó ",
    "lại phải win nữa à🙄🙄 ",
    "chậm vậy sao cứu được con đĩ mẹ mày nhanh lên đi chứ:)))  ",
    "chết cha nó sồn r  ",
    "con đĩ mẹ mày gào thét đê?😛  ",
    "mày gào lên con?😏  ",
    "sao cay tao dọ?  ",
    "mày sủa đi nè😛  ",
    "cave tỉnh lẽ phát biểu:)) ",
    "ra tín hiệu đê :))) ",
    "SOS con dái đú 🤣🤣🤢 ",
    "ớ ớ ớ :))) ",
    "chó ăn cứt :))) ",
    "chó đú sàn 👌🐶 ",
    "ỉa ra máu r à :))) ",
    "nghèo k có nghi lực à:)) ",
    "phản kháng đê :))) t win à ",
    "sủa đê 🤣🤣 ",
    "chó bú cứt🤣🤣👌",
    "hăng hái đê :)) ",
    "chậm dọ 🤣🤣 ",
    "óc dái cay r🤣🤣 ",
    "ăn hại phát biểu lẹ đê 🤣🤣 ",
    "óc dái :))) ",
    "ổn phải k? ",
    "ngu ớn 🤣🤣👌 ",
    "chó ăn cứt 🐶 ",
    "dái đú :)))) ",
    "yếu dữ ta😏😏 ",
    "con chó đần👉🤣 ",
    "ổn dữ chưa =))) ",
    "run ớn dạ :))) ",
    "óc đú 🤣🤣 ",
    "rồi xong 🤢🤢 ",
    "có thể hăng ko á  ",
    "ẻm cay doài =))) ",
    "cay tuột buồi 👉🤣",
    "ei ei =)) ",
    "em ei :3 ",
    "chạy à ",
    "mày sợ hả 🤢🤢 ",
    "coi ẻm sồn kìa🤣🤣 👌",
    "lại bá à :))) ",
    "sao chậm dữ ",
    "eo oyyy:3 ",
    "hú hú🤨 ",
    "sao ức chế dạ 😏😏 ",
    "con não cún bị chửi kìa 🤣🤣🐶 ",
    "mau đê :)) ",
    "hăng đê :))) ",
    "sủa mau đê =)) ",
    "tuột hứng cha :))) ",
    "tnh gà :))) ",
    "sao chậm chạp v :)) ",
    "óc dái 🤣🤣 ",
    "lồn cụ con đĩ đớ🤣🤣 ",
    "lưu loát lên đê 🤣🤣 ",
    "khựng dạ :))) ",
    "t mạnh lắm phải ko à :))) ",
    ":))) nhỏ mếu à ae ",
    "m nghèo mà ",
    "sợ t lắm à:3 ",
    "hả cu =))) ",
    "thấy tội quá:)) ",
    "thương ẻm cố gắng🤢🤘 ",
    "mà ngu🤣🤣 ",
    ":)) 🤣🤣 ",
    "cay lắm à :)) ",
    "nhạt nhoè v à ",
    "ko cảm hứng để hăng à :))) ",
    "xạo lồn à :))) ",
    "khóc đk :))) ",
    "cave tỉnh lẽ phát biểu:)) ",
    "ra tín hiệu đê :))) ",
    "SOS con dái đú 🤣🤣🤢 ",
    "ớ ớ ớ :))) ",
    "chó ăn cứt :))) ",
    "chó đú sàn 👌🐶 ",
    "ỉa ra máu r à :))) ",
    "nghèo k có nghi lực à:)) ",
    "phản kháng đê :))) t win à ",
    "cần cứu ko :)) ",
    "cố đi :3 ",
    "gáng lên đê :))) ",
    "sủa to lên🤣🤣 ",
    "phò nông thôn 🤢🤢 ",
    "óc cặc tỉnh lẽ =)))) ",
    "khoẻ ko 🤣🤣 ",
    "kkk ",
    "đói à🤣🐶👌 ",
    "ăn chưa à 🤣🤣 ",
    "chưa đk :))) ",
    "thấy kém cõi :)) ",
    "đú cứt kìa :))) ",
    "eo oyyy:3 ",
    "cố đê 🤣🤣 ",
    "thấy mày đơ đơ :))) ",
    "con cave 🤣🤣 ",
    "mạnh lên:))) ",
    "gõ mạnh lên đê:)) ",
    "thấy ngại ngùng z🤣🤘 ",
    "tự nhiên đê ",
    "mệt đk ",
    "cấm m ngưng ",
    "đĩ đầu đinh :))) ",
    "lẹ đê:)) ",
    "mày lag à :)) ",
    "m trầm cảm à :))) ",
    "tâm lí ko vững à :)) ",
    "cần thuốc à :)) ",
    "hấp hối hả🤣🤣 ",
    "khó thở dk :)) ",
    "cần oxi ko :))) ",
    "mày bệnh nặng lắm à :))) ",
    "tuột hứng cha :))) ",
    "tnh gà :))) ",
    "sao chậm chạp v :)) ",
    "óc dái 🤣🤣 ",
    "lồn cụ con đĩ đớ🤣🤣 ",
    "lưu loát lên đê 🤣🤣 ",
    "khựng dạ :))) ",
    "t mạnh lắm phải ko à :))) ",
    ":))) nhỏ mếu à ae ",
    "m nghèo mà ",
    "sợ t lắm à:3 ",
    "hả cu =))) ",
    "thấy tội quá:)) ",
    "thương ẻm cố gắng🤢🤘 ",
    "mà ngu🤣🤣 ",
    ":)) 🤣🤣 ",
    "cay lắm à :)) ",
    "nhạt nhoè v à ",
    "ko cảm hứng để hăng à :))) ",
    "xạo lồn à :))) ",
    "khóc đk :))) ",
    "cave tỉnh lẽ phát biểu:)) ",
    "ra tín hiệu đê :))) ",
    "SOS con dái đú 🤣🤣🤢 ",
    "ớ ớ ớ :))) ",
    "chó ăn cứt :))) ",
    "chó đú sàn 👌🐶 ",
    "ỉa ra máu r à :))) ",
    "nghèo k có nghi lực à:)) ",
    "phản kháng đê :))) t win à ",
    "kkk ",
    "m chết r à :))) ",
    "m nghèo mà em 😏🤣 ",
    "m thèm cứt t mà:)) ",
    "đĩ mẹ m ngu mà👉🤣 ",
    "m cay tao mà :)) ",
    "mày mồ côi mà đúng k🤣👈  ",
    "ai cho mày sủa tao cho mày sủa chưa?  ",
    "bị tao chọc cay hơn con chó luôn=)))  ",
    "cố đi sắp win rồi nè😏  ",
    "chừng nào mày mới làm lại tao dị?  ",
    "mẹ mày sắp tắt thở kìa ê  ",
    "đậu má mày gà mà sủa  ",
    "sủa điên đi mà sủa hăng lên mới vui😘  ",
    "mày mà ngưng một giây là con đĩ mẹ mày bả tắt đường thở á😏  ",
    "ê chó ngu mày sợ tao hả😂  ",
    "mày đú rõ mà sao mày đú dị?  ",
    "mẹ mày chết chưa con=)))  ",
    "ê bê đê sủa điên đi  ",
    "sao mày sủa chậm dị?  ",
      "m nghèo mà em 😏🤣 ",
    "m thèm cứt t mà:)) ",
    "đĩ mẹ m ngu mà👉🤣 ",
    "m cay tao mà :)) ",
    "mày mồ côi mà đúng k🤣👈  ",
    "ai cho mày sủa tao cho mày sủa chưa?  ",
    "bị tao chọc cay hơn con chó luôn=)))  ",
    "cố đi sắp win rồi nè😏  ",
    "chừng nào mày mới làm lại tao dị?  ",
    "mẹ mày sắp tắt thở kìa ê  ",
    "đậu má mày gà mà sủa  ",
    "sủa điên đi mà sủa hăng lên mới vui😘  ",
    "mày mà ngưng một giây là con đĩ mẹ mày bả tắt đường thở á😏  ",
    "ê chó ngu mày sợ tao hả😂  ",
    "mày đú rõ mà sao mày đú dị?  ",
    "mẹ mày chết chưa con=)))  ",
    "nào làm lại tao nói đê?  ",
    "bị tao chọc cay hơn con chó luôn😏  ",
    "sủa đi rồi tao tha?  ",
    "sủa điên lên cho mẹ?  ",
    "mày ngưng là con đĩ mẹ mày chết?  ",
    "cay tao lòi dái hả😏  ",
    "não chó cay à?🤣  ",
    "sao mày thảm dị=)))  ",
    "mẹ mày bị tao địt rách màn trinh mà🤪  ",
    "mẹ mày bị tao dã vào lồn=)))  ",
    "địt mẹ mày sướng tê con cặc=)))  ",
    "huhu nhìn mày như con cặc=)))  ",
    "mày loạn luân bà già hả=)))  ",
    "mẹ mày bị tao địt rên ư ử=)))  ",
    "địt mẹ mày sảng khoái quá đi😛  ",
    "tao địt mẹ mày nát lồn mà=)))  ",
    "Ê bóng lồn  ",
    "mẹ mày bị tao cưỡng hiếp=)))  ",
    "mẹ mày đưa lồn chó liếm à🤣👈  ",
    "mày óc cái lồn mà  ",
    "năn nỉ đi tao tha😏  ",
    "bú lồn tao đi🤪  ",
    "mày ẳng gì dị?😏  ",
    "nghe nói mày sợ tao?  ",
    "vô danh cấm sủa?😏  ",
    "gì mày thèm cứt tao hả=)))?  ",
    "sao mày lề mề dị con  ",
    "mày có tuổi hở?😏  ",
    "tuổi lồn ăn tao á😏?  ",
    "bị tao chửi sảng cặc đéo dám care:)))  ",
    "mạnh lên sao yếu đuối v con:)))  ",
    "mày run cặc chưa con:)))  ",
    "chậm vậy sao cứu được con đĩ mẹ mày nhanh lên đi chứ:)))  ",
    "chết cha nó sồn r  ",
    "con đĩ mẹ mày gào thét đê?😛  ",
    "mày sủa điên dại lên con?😏  ",
    "sao cay tao dọ?  ",
    "sủa đi nè hjhj thg béo😛  ",
    "sao mày xấu lồn gớm chó dị con?  ",
    "sao cay tao hả😏?  ",
    "sao mày giết mẹ vậy=)))  ",
    "mày gào đi con=)))  ",
    "nào ổn thì đú🤣👈  ",
    "ê bê đê lên ăn hôi lẹ😘  ",
      "mày loạn luân bà già hả=)))  ",
    "mẹ mày bị tao địt rên ư ử=)))  ",
    "địt mẹ mày sảng khoái quá đi😛  ",
    "tao địt mẹ mày nát lồn mà=)))  ",
    "Ê bóng lồn  ",
    "mẹ mày bị tao cưỡng hiếp=)))  ",
    "mẹ mày đưa lồn chó liếm à🤣👈  ",
    "mày óc cái lồn mà  ",
    "quỳ xuống năn nỉ t đi tao tha😏  ",
    "bú lồn tao đi🤪  ",
    "sao mày óc cặc dữ con=)))  ",
    "gặp cha là run hả?😂  ",
    "con đĩ mẹ mày thèm cứt tao dữ lắm=)))  ",
    "mày mất cha mất mẹ mà đúng k🤣👈  ",
    "ai cho mày sủa tao cho mày sủa chưa?  ",
    "bị tao chọc cay hơn con chó luôn=)))  ",
    "cố đi sắp win rồi nè😏  ",
    "chừng nào mày mới làm lại tao dị?  ",
    "mẹ mày bị t đụ đột quỵ ngoài nhà nghỉ kìa đem hòm ra nha   ",
    "đem 2 cái m với con gái mẹ m luôn nha thg béo kkk ",
    "sủa điên đi mà sủa hăng lên mới vui😘  ",
    "mày mà ngưng một giây là con đĩ mẹ mày bả tắt đường thở á😏  ",
    "ê chó ngu mày sợ tao hả😂  ",
    "mày đú rõ mà sao mày đú dị?  ",
    "mẹ mày chết chưa con=)))  ",
    "ê bê đê sủa điên đi  ",
    "sao mày sủa chậm dị?  ",
    "nào làm lại tao nói đê?  ",
    "bị tao chọc cay hơn con chó luôn😏  ",
    "sủa đi rồi đại ca tha nè thg óc?  ",
    "sủa điên lên cho mẹ?  ",
    "mày ngưng là con đĩ mẹ mày chết?  ",
    "cay tao lòi dái hả😏  ",
    "bem với cha mở đầu chó m ra nhe?🤣  ",
    "sao mày thảm vãi lồn cần t lau nước mắt không!!!!=)))  ",
    "mẹ mày bị tao địt rách màn trinh mà🤪  ",
    "mẹ mày bị tao dã vào lồn=)))  ",
    "địt mẹ mày sướng tê con cặc=)))  ",
    "huhu nhìn mày như con cặc=)))  ",
    "mày loạn luân bà già hả=)))  ",
    "mẹ mày bị tao địt rên ư ử=)))  ",
    "địt mẹ mày sảng khoái quá đi😛  ",
    "tao địt mẹ mày nát lồn mà=)))  ",
    "Ê bóng lồn  ",
    "mẹ mày đưa lồn chó liếm à🤣👈  ",
    "mày óc cái lồn mà  ",
    "quỳ xuống năn nỉ t đi tao tha😏  ",
    "bú lồn tao đi🤪  ",
    "mày ẳng gì dị?😏  ",
    "nghe nói mày sợ tao?  ",
    "vô danh cấm sủa?😏  ",
    "gì mày thèm cứt tao hả=)))?  ",
    "sao mày lề mề dị con  ",
    "mày có tuổi hở?😏  ",
    "tuổi lồn ăn tao á😏?  ",
    "ê thằng bê đê bóng lộ 🤣🤣 ",
    "để cha khai khẩu cho nha 😛😛 🤣🤣 ",
    "bú cứt cha khen ngon đúng kh🤣🤣👌",
    "hăng nhanh :)) ",
    "lag r hả thg óc dái 🤣🤣 ",
    "óc dái cay r🤣🤣 ",
    "ăn hại phát biểu lẹ đê 🤣🤣 ",
    "Mẹ m bị tao đụ rách lồn mà🤣 :))) ",
    "Mẹ Mày bị t địt sập cầu sập cống . ",
    "Cha m chặt cặc ăn🤣🤣👌 ",
    "Gà đĩ🐔 mà đòi ăn ae tao à 🍔🐶 ",
    "Súc sinh k trình mà đòi bem anh hả th đú:)))) ",
    "yếu dữ ta😏😏 ",
    "Đẻ bằng tinh trùng fake👉🤣 ",
    "ổn dữ chưa =))) ",
    "Cha là chúa thánh🐒🎶 đên đây để bịt mõm mấy tk anh hùng:))) ",
    "Mày Sài ngôn tiền sử à kakaa 🤣🤣 ",
    "M cạn ngôn à cn đĩ ngu ngôn tiền sử cmnr🤢🤢 ",
    "có thể hăng ko á  ",
    "ẻm cay doài =))) ",
    "cay tuột buồi 👉🤣",
    "Úi Úi thg cay cha tao nên chặt cu kìa 🤣 =)) ",
    "Mẹ m cắt cổ chết:3 ",
    "CÂM LÀ CẢ NHÀ M CHẾT DƯỚI 💀TAY CHA😣∋⓪①②③( =ノωヽ=)◉‿◉🐮🐮 ",
    "Cha win cmnr❦❦❦❦🤢🤢 ",
    "thằng mồ côi khốn khổ 😮‍💨😮‍💨🤣🤣 👌",
    "lại bá à :))) ",
    "sao chậm dữ ",
    "thằng bê đê ảo cặc đòi cân và cái kết:))):3 ",
    "bem với cha phải banh đầu óc chó ra đáp lại nghe chưa🤨 ",
    "sao ức chế dạ 😏😏 ",
    "con não cún bị chửi kìa 🤣🤣🐶 ",
    "Lũ đú ấm ức cha mày rõ mà😗❗",
    "Sao rồi ổn lòi lìa hả 🤔",
    "Cha mày đấng mxh mà lũ ngu🤣",
    "Cay cha mày lắm r phải kh",
    "Đái ra máu r kìa cn ngu ơi🤣",
    "Cưng xạo lồn bịa chuyện là hay😗",
    "Chứ trình mày làm gì có tuổi ăn anh🤣",
    "Cưng hăng hái 1 cách bất thường à🤣",
    "Cay cú anh trong lòng mà không làm đc gì🤔🌶", 
    "Cay đỏ bướm rồi à cn ngu🌶❗",
    "Thk cặc cay anh đỏ dái mẹ r🌶❗🤪",
    "Khi nào cs trình v cn ôn thú",
    "Mặt mày như cn quái thai từ trong bào thai v🤪",
    "Ê con suy tàn đạo đức🤪",
    "Nhân cách thối nát đáy của tạp chủng 🤣",
    "Cái con không có địa vị bằng 1 cn súc vật nữa🤪🤣",
    "Cha mày gõ cho mày nguyên 1 tràn lan đại hải🤣",
    "Gõ cho mày tá hỏa tâm tinh🤪",
    "Gõ cho mày siêu thoát quá thế giới bên kia🤣",
    "Con đỉ bị cha hành hạ🤪",
    "Cn tinh tinh mặt cặc❗",
    "Cn thú mặt người",
    "Cn khỉ mặt nhân loại🐵❗",
    "Cn tạp nham cay anh🌶❗",
    "Khóc r à em🤣❗",
    "Bất ổn r à🤣",
    "Mếu máo mẹ mày r🤣",
    "Sao rồi em gái🤣",
    "Mày bị cha cho cay cú mà🌶🤣",
    "Về méc mẹ rồi à🤣",
    "Sao không hăng nx đi🤣",
    "Gõ yếu vậy à🤣",
    "Gõ sồn máu lồn mày lên",
    "Hăng hái lên cha xem🤣",
    "Cay cú nên hóa rồ rồi à🤣",
    "Mới gõ tí đã đuối rồi🤣",
    "Bị anh cho ngậm đống hành trong mõm r🤣🤣",
    "Gõ sồn sồn lên xôm lên xem nào🤣",
    "Bất ổn cmnr🤣",
    "Não bị cha mày cho tàn phế r à🤣",
    "Ê sao cn thú nhai ngôn r🤣",
    "Sức cùng lực kiệt r à🤣",
    "Ê cay đái kh còn giọt máu r à🤣",
    "Cha mày chuyên trị lũ đú mà🤣",
    "Cưng sao v hả🤣",
    "Không hăng như lúc đầu nữa hả🤣",
    "Eo ôi:>🤪",
    "Còn sống kh v😗",
    "Mày bị cha hành mà:3",
    "Cha cấm mày bịa chuyện nha🤔",
    "Cha quin mà cn thú êy🤪",
    "Hóng quin đc cha lắm hỏ🤪",
    "Ê cn quái thú🤪",
    "Mày là cn quái thú giữa rừng xanh mà🤪",
    "Mày tưởng mày đang đóng vai ng đẹp và quái vật hả🤪",
    "Mày tưởng mày đang đóng vai ng đẹp và quái vật hả🤪",
    "Thoát ra khỏi cái mộng tưởng đó đi nhóc🤪",
    "Sao bị cha chửi mà tha hóa lun r🤪",
    "Sống phèn quá v cn thú đú êy😳",
    "Mếu cha mẹ r🤪",
    "Cay cú mẹ r🌶❗",
    "Lgbt bày binh bố trận dồn cha hả🤪❗",
    "Dồn ngu mà cũng đòi dồn❗🦋",
    "Nhìn lũ tật cầm cái phím tắt hăng ghê🤣",
    "Cha mày chúa tể trị lũ đú🤪",
    "Cha mày bón cứt dô mõm m nè😏",
    "Ê đỉ ngu🤣",
    "Sao rồi ổn kh",
    "Hay ổn lòi lìa😴😳",
    "Nhìn mặt m là bt không ổn r😳",
    "Cn tinh tinh bị cha đọa đày😁",
    "Bị cha mày đọa đày xuống diêm la địa phủ😗",
    "Để đầu thai chuyển kiếp thành súc vật🤣",
    "Đừng cay cha mà làm liều❗❗",
    "Nhìn bản mặt mày là đủ hiểu cay cỡ nào🌶",
    "Mày đái ra máu r kìa🌶🤣",
    "Nhanh tay lên nào🤣",
    "Nhanh tay múc nc máu lồn cho tk cha mày uống lẹ🤣",
    "Rồi lun cn ôn thú bị anh sỉ nhục mẹ r🤣",
    "Sỉ nhục như cn động vật bậc thấp🤣",
    " ngu si 4 chi phát triển🤪",
    "Tự nhiên cái hăng ngang dị🤣",
    "Hăng ngang làm anh sợ ghê 😱",
    "Hăng lên đc tí r ngủm r à🤪",
    "Đái ra máu xè xè r🤣❗",
    "Ăn năn xám hối r à ❗🤣",
    "Cay quá nên uống nc đái chó cho đỡ cay đi em🤣",
    "Mếu chết đỉ mẹ mày đi",
    "Đầu thai mẹ mày đi cn tạp chủng🤣",
    "Cn ngu xi đần độn dốt nát🤣",
    "Bị cha cho tha hóa thành cchó ngu dốt🤣",
    "Sao mày ngu như 🐮 v",
    "Cay cay cay cha rồi🤣",
    "Ai cho mày cay cha hả🤣",
    "Cay chừa phần người ta với🤣",
    "Cay ht phần thiên hạ là sao dị 🤨",
    "Ê cn thú hoang dã🤣",
    "Cn dị tật bẩm sinh liệt não",
    "Hấp hối mẹ mày rồi à🤨",
    "Cha mày trùm đấng mxh ai làm lại anh đâu😁",
    "Mày khóc rồi à🤣",
    "Con bào thai trong ống nghiệm cũng bt mếu à🤣",
    "Mày sủa như cách cn chó nhà mày sủa đê🤣", 
    "Ê sao cay cú cha mày rồi😳",
    "Ai cho mày cay cha hả😗",
    "Cn tinh tinh đội lót nhân dân hại dân lành🤣",
    "Cạn ngôn r hả cn thú ngu êy",
    "Sao lặp ngôn liên tục v🤣",
    "Gõ dài dòng kh dame thì gõ làm gì🤣",
    "Mày là cn phò trường chinh mà🤣",
    "Cn thú mại dâm bán dâm mà như bán trinh hoa hậu v🤣",
    "Ê cn đỉ phát ngôn xàm bậy🤣",
    "Mày đừng tự vả dô mặt m nữa🤣",
    "Nhìn mày là bt kh ổn r!",
    "Mày bt anh là chuyên trừng trị những thể loại như m kh",
    "Sao mày đú quá v🤣", 
    "Khi nào ht đú hả cn thú ngu",
    "Chắc xog quả này chắc ht đú ha",
    "Ê cn thú ngu ngục bẩm sinh",
    "Mày là cn thú ms đẻ ra đã ngu sẵn r🤣",
    "Ê cn âm binh đầu đường xó chợ🤪",
    "Mày hăng mạnh mẽ lên đê🤪",
    "Sao tự nhiên yếu xìu như xìu cặc v🤣",
    "Mẹ mày bị mày loạn luân đụ rung lồn mà🤣",
    "Cặc chưa mọc lông mà đòi đụ này đụ kia🤣",
    "con chó ngu ngục lên thể hiện trình bị anh sút🤣", 
    "thằng ngu đang cố tỏ ra mình ổn à", 
    "ơ ơ ơ sao em lại hăng ", 
    "dân war 2024 hăng ròi kìa ae", 
    "bị anh chọc cho tê cu à ", 
    "nhìn tk óc dái đú đang đú bot nhìn ngu vậy 🤣", 
    "ơ tk ngu ai treo vậy em ", 
    "tự nhiên treo vậy tk gà bí ngôn", 
    "ai giả bộ sợ cho em nó đỡ quê đê😝", 
    "tk ngu ăn cứt tao mà ra oai à", 
    "sao em đú dữ vậy tỉnh lên đê",
      "thg ngu va tí kh 🤣🤣 ",
    "vô danh cấm sủa?😏  ",
    "gì mày thèm cứt tao hả=)))?  ",
    "sao mày lề mề dị con  ",
    "mày có tuổi hở?😏  ",
    "tuổi lồn ăn tao á😏?  ",
    "tao đụ má mày ná thở mà😛 ",
    "cấm hoảng loạn ",
    "lại phải win nữa à🙄🙄 ",
    "kkk ",
    "tuột hứng cha :))) ",
    "tnh gà :))) ",
    "sao chậm chạp v :)) ",
    "óc dái 🤣🤣 ",
    "lồn cụ con đĩ đớ🤣🤣 ",
    "lưu loát lên đê 🤣🤣 ",
    "khựng dạ :))) ",
    "t mạnh lắm phải ko à :))) ",
    ":))) nhỏ mếu à ae ",
    "m nghèo mà ",
    "sợ t lắm à:3 ",
    "hả cu =))) ",
    "thấy tội quá:)) ",
    "thương ẻm cố gắng🤢🤘 ",
    "mà ngu🤣🤣 ",
    ":)) 🤣🤣 ",
    "cay lắm à :)) ",
    "nhạt nhoè v à ",
    "ko cảm hứng để hăng à :))) ",
    "xạo lồn à :))) ",
    "khóc đk :))) ",
    "cave tỉnh lẽ phát biểu:)) ",
    "ra tín hiệu đê :))) ",
    "SOS con dái đú 🤣🤣🤢 ",
    "ớ ớ ớ :))) ",
    "chó ăn cứt :))) ",
    "chó đú sàn 👌🐶 ",
    "ỉa ra máu r à :))) ",
    "nghèo k có nghi lực à:)) ",
    "phản kháng đê :))) t win à ",
    "sủa đê 🤣🤣 ",
    "chó bú cứt🤣🤣👌",
    "hăng hái đê :)) ",
    "chậm dọ 🤣🤣 ",
    "óc dái cay r🤣🤣 ",
    "ăn hại phát biểu lẹ đê 🤣🤣 ",
    "óc dái :))) ",
    "ổn phải k? ",
    "ngu ớn 🤣🤣👌 ",
    "chó ăn cứt 🐶 ",
    "dái đú :)))) ",
    "yếu dữ ta😏😏 ",
    "con chó đần👉🤣 ",
    "ổn dữ chưa =))) ",
    "run ớn dạ :))) ",
    "óc đú 🤣🤣 ",
    "rồi xong 🤢🤢 ",
    "có thể hăng ko á  ",
    "ẻm cay doài =))) ",
    "cay tuột buồi 👉🤣",
    "ei ei =)) ",
    "em ei :3 ",
    "chạy à ",
    "mày sợ hả 🤢🤢 ",
    "coi ẻm sồn kìa🤣🤣 👌",
    "lại bá à :))) ",
    "sao chậm dữ ",
    "eo oyyy:3 ",
    "hú hú🤨 ",
    "sao ức chế dạ 😏😏 ",
    "con não cún bị chửi kìa 🤣🤣🐶 ",
    "mau đê :)) ",
    "hăng đê :))) ",
    "sủa mau đê =)) ",
    "tuột hứng cha :))) ",
    "tnh gà :))) ",
    "sao chậm chạp v :)) ",
    "óc dái 🤣🤣 ",
    "lồn cụ con đĩ đớ🤣🤣 ",
    "lưu loát lên đê 🤣🤣 ",
    "khựng dạ :))) ",
    "t mạnh lắm phải ko à :))) ",
    ":))) nhỏ mếu à ae ",
    "m nghèo mà ",
    "sợ t lắm à:3 ",
    "hả cu =))) ",
    "thấy tội quá:)) ",
    "thương ẻm cố gắng🤢🤘 ",
    "mà ngu🤣🤣 ",
    ":)) 🤣🤣 ",
    "cay lắm à :)) ",
    "nhạt nhoè v à ",
    "ko cảm hứng để hăng à :))) ",
    "xạo lồn à :))) ",
    "khóc đk :))) ",
    "cave tỉnh lẽ phát biểu:)) ",
    "ra tín hiệu đê :))) ",
    "SOS con dái đú 🤣🤣🤢 ",
    "ớ ớ ớ :))) ",
    "chó ăn cứt :))) ",
    "chó đú sàn 👌🐶 ",
    "ỉa ra máu r à :))) ",
    "nghèo k có nghi lực à:)) ",
    "phản kháng đê :))) t win à ",
    "cần cứu ko :)) ",
    "cố đi :3 ",
    "gáng lên đê :))) ",
    "sủa to lên🤣🤣 ",
    "phò nông thôn 🤢🤢 ",
    "óc cặc tỉnh lẽ =)))) ",
    "khoẻ ko 🤣🤣 ",
    "kkk ",
    "đói à🤣🐶👌 ",
    "ăn chưa à 🤣🤣 ",
    "chưa đk :))) ",
    "thấy kém cõi :)) ",
    "đú cứt kìa :))) ",
    "eo oyyy:3 ",
    "cố đê 🤣🤣 ",
    "thấy mày đơ đơ :))) ",
    "con cave 🤣🤣 ",
    "mạnh lên:))) ",
    "gõ mạnh lên đê:)) ",
    "thấy ngại ngùng z🤣🤘 ",
    "tự nhiên đê ",
    "mệt đk ",
    "cấm m ngưng ",
    "đĩ đầu đinh :))) ",
    "lẹ đê:)) ",
    "mày lag à :)) ",
    "m trầm cảm à :))) ",
    "tâm lí ko vững à :)) ",
    "cần thuốc à :)) ",
    "hấp hối hả🤣🤣 ",
    "khó thở dk :)) ",
    "cần oxi ko :))) ",
    "mày bệnh nặng lắm à :))) ",
    "tuột hứng cha :))) ",
    "tnh gà :))) ",
    "sao chậm chạp v :)) ",
    "óc dái 🤣🤣 ",
    "lồn cụ con đĩ đớ🤣🤣 ",
    "lưu loát lên đê 🤣🤣 ",
    "khựng dạ :))) ",
    "t mạnh lắm phải ko à :))) ",
    ":))) nhỏ mếu à ae ",
    "m nghèo mà ",
    "sợ t lắm à:3 ",
    "hả cu =))) ",
    "thấy tội quá:)) ",
    "thương ẻm cố gắng🤢🤘 ",
    "mà ngu🤣🤣 ",
    ":)) 🤣🤣 ",
    "cay lắm à :)) ",
    "nhạt nhoè v à ",
    "ko cảm hứng để hăng à :))) ",
    "xạo lồn à :))) ",
    "khóc đk :))) ",
    "cave tỉnh lẽ phát biểu:)) ",
    "ra tín hiệu đê :))) ",
    "SOS con dái đú 🤣🤣🤢 ",
    "ớ ớ ớ :))) ",
    "chó ăn cứt :))) ",
    "chó đú sàn 👌🐶 ",
    "ỉa ra máu r à :))) ",
    "nghèo k có nghi lực à:)) ",
    "phản kháng đê :))) t win à ",
    "kkk ",
    "m chết r à :))) ",
    "m nghèo mà em 😏🤣 ",
    "m thèm cứt t mà:)) ",
    "đĩ mẹ m ngu mà👉🤣 ",
    "m cay tao mà :)) ",
    "con óc cứt thối🤢🤢 ",
    "Lũ đú ấm ức cha mày rõ mà😗❗",
    "Sao rồi ổn lòi lìa hả 🤔 ",
    "Cha mày đấng mxh mà lũ ngu🤣 ",
    "Cay cha mày lắm r phải kh ",
    "Đái ra máu r kìa cn ngu ơi🤣 ",
    "Cưng xạo lồn bịa chuyện là hay😗 ",
    "Chứ trình mày làm gì có tuổi ăn anh🤣 ",
    "Cưng hăng hái 1 cách bất thường à🤣 ",
    "Cay cú anh trong lòng mà không làm đc gì🤔🌶❗ ", 
    "Cay đỏ bướm rồi à cn ngu🌶❗ ",
    "Thk cặc cay anh đỏ dái mẹ r🌶❗🤪 ",
      "mẹ m bị t địt rách lồn mà ??😜😈👈💪 ",
    "m câm à tk ngu😆 {name)",
    "mẹ m hứng mồm ăn tinh t mà 😍😍 ",
    "m óc giái đĩ chó à tk svat😜 ",
    "m thú hoang mà tk ngu😜 ",
    "t sẻo lồn mẹ m nướng mà ",
    "cha chặt giái bố m để cho mẹ m ăn mà🙂😎 ",
    "tk ngu liếm đít cha à🥸 ",
    "m như 1 con svat thế hả😆 ",
    "m có não k thế ???💀 ",
    "m bại trc a mà tk não chó🤖 ",
    "m là tk ăn hôi mà m kbt à😼 ",
    "cha mãi win nè👅 ",
    "tk tật ăn hôi cha m🖐 ",
    "tk óc giái ",
    "bố m là đấng mxh mà tk óc 😇 ",
    "m có não k tk chó ngu ",
    "m là culi của cha mà🤡 ",
    "cha mẹ m bị t chặt giái mà😹 ",
    "mẹ m bị t móc lồn bắt tung tóe kìa ",
    "mẹ m bị mấy e sida nhấp liệt dương👽 ",
    "cha m bị t hành như 1 con chó nè 👹👹 ",
    "t cho mẹ m bú cu t mà 😽 ",
    "cíu mẹ m đi tk bất hiếu 😹 ",
    "m ngu hay j thế ?😵‍💫 ",
    "m ảo đú à tk culi🎃 ",
    "ngôn của m lm cay đc cha à 👻👻 ", 
    "đĩ mẹ m đó tk tật👽 ",
    "m là người ngoài hành tinh à 💩🤮 ",
    "cha mẹ m đang cần m cầu cíu đó 😪 ",
    "mẹ m còn đang đợi t đút cặc vô lồn đó 🤣 ",
    "tk cha m bị t cho uống thức nứng cặc 🤩🤩 ",
    "cha mẹ m bị t dí giái vô m kìa🤪 ",
    "cha mẹ m k lmj đc t kìa 🤭 ",
    "cha m bị mù r đó tk ngu ạ 😱 ",
    "mẹ m bị t sẻo vú mà m k bt à🤔🤔 ",
    "mẹ m bị t chém bay cả đầu🙄👌👈 ",
    "mẹ m còn khỏa thân quỳ trc t kìa 🦶🫵 ",
    "m cíu mẹ m đi 🦾 ",
    "m bị ngu à tk tật👅 ",
    "m như tk thú hoang vại 👩‍🦰 ",
    "tk trẩu chx ra đời mà đã chs vs cha à👧 ",
    "cái loại đáy mxh💩💩 ",
    "mẹ m đi hứng cứt của t ăn ngon lành😈 ",
    "cha m bị t móc cả trĩ ra r kìa 🙀 ",
    "m là tk bất hiểu à 👾 ",
    "m là tk thú hoang hay j mà m câm vậy😹 ",
    "sủa đê cha nghe 🙀 ",
    "cha đợi từ mày đó 👹 ",
    "m là tk đĩ ngu 🤕 ",
    "cha bất bại mọi sàn war mà ?? 👹👹 ",
    "má thế t là đấng bà nó r 😮‍💨 ",
    "t đang hành loại svat như m mà😼 ",
    "m còn k bằng con chó của t kìa ☠️ ",
    "m bị t dí cặc vô mặt mà🥴 ",
    "t địt con ghệ m bay lồn mà ",
      "🤣🤣🤣",
    "t bắt 3 đứa nó dí vô nhau ",
    "Bú Cặc Ah lẹ nè e ",
    "M ôm hận ah đến kiếp sau hả🤨 ",
    "sủa lẹ đi tk ngu m cay ah à🌶 ",
    "Hăng lẹ đi tk tật mồ côi 🤣🤣🤣 ",
    "Hay đi láy đt mẹ gõ vậy ",
    "bố địt chết mẹ m h ",
    "tk óc chó mồ côi cay bố kìa 🤣🤣 ",
    "con chó óc cặc hăng lẹ lên  ",
    "Mày húp máu lồn mẹ mày khen béo à ",
    "Con culi lên cha biểu phát nào ",
    "Ko lmj dc anh cái cay ah à tk não chó ",
    "Kiếm ngôn nào sát thương tí dc k ",
    "lm bố cay dc ko 🫣🫣🫣 ",
    "Mày bần hèn vậy à thằng óc cứt ",
    "con chó cay cha hả 🫣🫣🫣 ",
    "M lấy xác chuột nhét vô lồn mẹ m à ",
    "sợ bố mà xạo lồn à con 👉🤣🤣🤣 ",
    "Tk não vô sinh ngu ngục quỳ lạy bố đê Kiếm ngôn nào sát thương tí dc k ",
    "Tk não vô sinh ngu ngục quỳ lạy bố đê kkk ",
    "bất ổn à tk ngu ơi ",
    "ngôn dell có sát thương à 🫣🫣 ",
    "sao m yếu z tk bede m câm t chặt đầu cha m đó ",
    "con chó phèn à ",
    "ao vừa địt vừa hát như Quang Thọ, địt xong rồi cầm cờ lê tao gõ mõ boong boong, cầm cờ lê tao gõ mõ coong coong. ☺ ",
    "óc dái bede cay à🤣🤣 ",
      "dái đú cay ẻ r ",
      "nổ trứng dái chưa em "
  ];
  if (!spamThreads.has(threadID)) {
    let i = 0; 
    spamThreads.set(threadID, { i });
    while (spamThreads.has(threadID)) {
      const content = vtuann[i % vtuann.length];
      await api.sendMessage({
        body: `${content}` + name, mentions: arraytag },threadID)
      await delay(timedelay * 1000);
      i++;
      spamThreads.get(threadID).i = i; 
    }
  } else {
    api.sendMessage(`Chao em nha<3!`, threadID, messageID);
  }
};